/**
 * The play-through test: boot the entry scene, start a session through the
 * game's IPlaythroughDriver, act until it ends, and leave a record of what
 * happened.
 *
 * The generated boot test proves the framework comes up; it drives nothing, so
 * its recording is the un-started game holding still. This test plays. It
 * binds to exactly one contract — Strada.Core.Play.IPlaythroughDriver, which
 * every game built on Strada.Core registers as an adapter over its own flow
 * and input services — so the same generated test serves every game and no
 * game's type names, scene names or rules appear here. A game that registers
 * no driver is recorded as such and fails the test: it cannot be proven
 * playable.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { chooseTestDir, hasTestFramework } from '../unity-scene/boot-smoke-test.js';

export const PLAYTHROUGH_TEST_CLASS = 'StradaPlaythroughTest';
export const PLAYTHROUGH_TEST_FILE = `${PLAYTHROUGH_TEST_CLASS}.cs`;
export const PLAYTHROUGH_RECORD_FILE = 'playthrough.json';
export const PLAYTHROUGH_ASSEMBLY = 'Strada.Generated.PlaythroughTests';
/** The contract the test drives; a game registers one in its service container. */
export const PLAYTHROUGH_DRIVER_TYPE = 'Strada.Core.Play.IPlaythroughDriver';

/** The C# source of the test and its assembly definition. */
export function buildPlaythroughTest(sceneName: string): { source: string; asmdef: string } {
  const source = `// Generated by unity_playthrough. Rewritten on every run; do not edit.
//
// Boots the entry scene, starts a session through the game's
// ${PLAYTHROUGH_DRIVER_TYPE}, acts until the session ends, records checkpoint
// frames, and writes ${PLAYTHROUGH_RECORD_FILE} with what happened.
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using Strada.Core.Bootstrap;
using Strada.Core.Play;

public class ${PLAYTHROUGH_TEST_CLASS}
{
    [Serializable]
    public class Record
    {
        public string scene;
        public int session;
        public string driverType;
        public string missing;
        public string phaseAfterBoot;
        public bool autoStarted;
        public bool startAccepted;
        public List<string> phasesSeen = new List<string>();
        public int actions;
        public string outcome;
        public bool reachedOutcome;
        public int framesCaptured;
        public float elapsedSeconds;
        public List<string> errors = new List<string>();
    }

    const int Width = 1280;
    const int Height = 720;
    const int MaxFrames = 40;
    const int FramesBetweenCaptures = 15;

    static string Env(string name, string fallback)
    {
        var v = Environment.GetEnvironmentVariable(name);
        return string.IsNullOrEmpty(v) ? fallback : v;
    }

    static int EnvInt(string name, int fallback)
    {
        int parsed;
        return int.TryParse(Environment.GetEnvironmentVariable(name), out parsed) ? parsed : fallback;
    }

    static string Phase(IPlaythroughDriver driver)
    {
        try { return driver.Phase ?? "null"; }
        catch (Exception e) { return "error:" + e.GetType().Name; }
    }

    [UnityTest]
    public IEnumerator TheGameCanBePlayedToAnOutcome()
    {
        var record = new Record();
        record.scene = Env("STRADA_PLAYTHROUGH_SCENE", ${JSON.stringify(sceneName)});
        record.session = EnvInt("STRADA_PLAYTHROUGH_SESSION", 1);
        record.driverType = ${JSON.stringify(PLAYTHROUGH_DRIVER_TYPE)};
        var maxActions = EnvInt("STRADA_PLAYTHROUGH_MAX_ACTIONS", 60);
        var deadlineSeconds = EnvInt("STRADA_PLAYTHROUGH_DEADLINE_S", 45);
        var captureDir = Env("STRADA_CAPTURE_DIR", null);
        var jsonPath = Env("STRADA_PLAYTHROUGH_JSON", captureDir == null ? null : Path.Combine(captureDir, ${JSON.stringify(PLAYTHROUGH_RECORD_FILE)}));
        var started = Time.realtimeSinceStartup;

        Application.LogCallback watch = (condition, stackTrace, type) =>
        {
            if ((type == LogType.Error || type == LogType.Exception || type == LogType.Assert) && record.errors.Count < 20)
                record.errors.Add("[" + type + "] " + condition);
        };
        Application.logMessageReceived += watch;
        LogAssert.ignoreFailingMessages = true;

        RenderTexture target = null;
        Texture2D readback = null;
        Camera camera = null;
        var overlays = new List<Canvas>();
        try
        {
            if (!Application.CanStreamedLevelBeLoaded(record.scene))
            {
                record.missing = "scene " + record.scene + " is not in Build Settings";
                Assert.Fail(record.missing);
            }
            yield return SceneManager.LoadSceneAsync(record.scene, LoadSceneMode.Single);

            var bootDeadline = Time.realtimeSinceStartup + 10f;
            while (Time.realtimeSinceStartup < bootDeadline && GameBootstrapper.Services == null)
                yield return null;
            if (GameBootstrapper.Services == null)
            {
                record.missing = "GameBootstrapper.Services stayed null for 10 s";
                Assert.Fail(record.missing);
            }

            IPlaythroughDriver driver = null;
            var serviceDeadline = Time.realtimeSinceStartup + 10f;
            while (Time.realtimeSinceStartup < serviceDeadline && driver == null)
            {
                try { GameBootstrapper.Services.TryGet(out driver); } catch { driver = null; }
                if (driver == null) yield return null;
            }
            if (driver == null)
            {
                record.missing = "the game registers no " + record.driverType + " — it cannot be played by the framework";
                Assert.Fail(record.missing);
            }

            // Does the game start play by itself? Two seconds of idling answer that.
            var idleDeadline = Time.realtimeSinceStartup + 2f;
            while (Time.realtimeSinceStartup < idleDeadline) yield return null;
            record.phaseAfterBoot = Phase(driver);
            try { record.autoStarted = driver.IsSessionActive; } catch { record.autoStarted = false; }

            if (captureDir != null)
            {
                Directory.CreateDirectory(captureDir);
                camera = Camera.main != null ? Camera.main : (Camera.allCameras.Length > 0 ? Camera.allCameras[0] : null);
                if (camera != null)
                {
                    target = new RenderTexture(Width, Height, 24);
                    readback = new Texture2D(Width, Height, TextureFormat.RGB24, false);
                    foreach (var canvas in UnityEngine.Object.FindObjectsByType<Canvas>(FindObjectsSortMode.None))
                        if (canvas.renderMode == RenderMode.ScreenSpaceOverlay) overlays.Add(canvas);
                    foreach (var canvas in overlays)
                    {
                        canvas.renderMode = RenderMode.ScreenSpaceCamera;
                        canvas.worldCamera = camera;
                    }
                }
            }
            Capture(record, captureDir, camera, target, readback);

            if (record.autoStarted)
                record.startAccepted = true;
            else
            {
                try { record.startAccepted = driver.StartSession(record.session); }
                catch (Exception e)
                {
                    record.startAccepted = false;
                    if (record.errors.Count < 20) record.errors.Add("[StartSession] " + e.GetType().Name + ": " + e.Message);
                }
            }
            yield return null;

            var playDeadline = Time.realtimeSinceStartup + deadlineSeconds;
            var frame = 0;
            var last = "";
            while (Time.realtimeSinceStartup < playDeadline)
            {
                var phase = Phase(driver);
                if (phase != last) { record.phasesSeen.Add(phase); last = phase; }
                PlaythroughOutcome outcome;
                try { outcome = driver.Outcome; } catch { outcome = PlaythroughOutcome.None; }
                if (outcome != PlaythroughOutcome.None)
                {
                    record.outcome = outcome.ToString();
                    record.reachedOutcome = true;
                    break;
                }
                if (record.actions < maxActions)
                {
                    try { if (driver.Act()) record.actions++; }
                    catch (Exception e) { if (record.errors.Count < 20) record.errors.Add("[Act] " + e.GetType().Name + ": " + e.Message); }
                }
                yield return null;
                frame++;
                if (frame % FramesBetweenCaptures == 0) Capture(record, captureDir, camera, target, readback);
            }
            if (!record.reachedOutcome) record.outcome = "None";
            Capture(record, captureDir, camera, target, readback);

            Assert.IsTrue(record.startAccepted, "The driver refused to start session " + record.session + ".");
            Assert.IsTrue(
                record.reachedOutcome,
                "Session " + record.session + " never ended after " + record.actions + " actions in " + deadlineSeconds
                + " s; last phase " + last + ".");
        }
        finally
        {
            record.elapsedSeconds = Time.realtimeSinceStartup - started;
            Application.logMessageReceived -= watch;
            LogAssert.ignoreFailingMessages = false;
            foreach (var canvas in overlays)
            {
                if (canvas == null) continue;
                canvas.renderMode = RenderMode.ScreenSpaceOverlay;
                canvas.worldCamera = null;
            }
            if (camera != null) camera.targetTexture = null;
            RenderTexture.active = null;
            if (target != null) target.Release();
            if (jsonPath != null)
            {
                try
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(jsonPath));
                    File.WriteAllText(jsonPath, JsonUtility.ToJson(record, true));
                }
                catch (Exception e) { Debug.LogWarning("playthrough record not written: " + e.Message); }
            }
        }
    }

    static void Capture(Record record, string dir, Camera camera, RenderTexture target, Texture2D readback)
    {
        if (dir == null || camera == null || target == null || readback == null || record.framesCaptured >= MaxFrames) return;
        try
        {
            var previous = camera.targetTexture;
            camera.targetTexture = target;
            camera.Render();
            RenderTexture.active = target;
            readback.ReadPixels(new Rect(0, 0, Width, Height), 0, 0);
            readback.Apply();
            RenderTexture.active = null;
            camera.targetTexture = previous;
            File.WriteAllBytes(Path.Combine(dir, "frame_" + record.framesCaptured.ToString("D5") + ".png"), readback.EncodeToPNG());
            record.framesCaptured++;
        }
        catch (Exception e)
        {
            if (record.errors.Count < 20) record.errors.Add("[Capture] " + e.GetType().Name + ": " + e.Message);
        }
    }
}
`;
  const asmdef = JSON.stringify(
    {
      name: PLAYTHROUGH_ASSEMBLY,
      rootNamespace: '',
      references: ['Strada.Core', 'UnityEngine.TestRunner', 'UnityEditor.TestRunner'],
      includePlatforms: [],
      excludePlatforms: [],
      allowUnsafeCode: false,
      // Same shape as the boot test's asmdef: overrideReferences drops the
      // engine modules the capture needs (measured there, CS0103 on ScreenCapture).
      overrideReferences: false,
      precompiledReferences: [],
      autoReferenced: false,
      defineConstraints: ['UNITY_INCLUDE_TESTS'],
      versionDefines: [],
      noEngineReferences: false,
    },
    null,
    2,
  );
  return { source, asmdef };
}

export interface PlaythroughEmission {
  readonly written: boolean;
  readonly reason?: string;
  readonly paths: string[];
  readonly dir?: string;
}

/**
 * Write the test beside the generated boot test, in its own folder so the two
 * assemblies do not share one directory (Unity allows one asmdef per folder).
 */
export function emitPlaythroughTest(projectPath: string, sceneName: string): PlaythroughEmission {
  if (!hasTestFramework(projectPath)) {
    return {
      written: false,
      reason: 'com.unity.test-framework is not in Packages/manifest.json — no play-mode test can compile, so none was written.',
      paths: [],
    };
  }
  const base = chooseTestDir(projectPath) ?? join(projectPath, 'Assets/Tests/PlayMode');
  const dir = join(base, 'Playthrough');
  const { source, asmdef } = buildPlaythroughTest(sceneName);
  try {
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, PLAYTHROUGH_TEST_FILE), source);
    writeFileSync(join(dir, `${PLAYTHROUGH_ASSEMBLY}.asmdef`), asmdef);
  } catch (error) {
    return { written: false, reason: `could not write the play-through test: ${String(error)}`, paths: [] };
  }
  const rel = dir.slice(projectPath.length + 1).replace(/\\/g, '/');
  return { written: true, dir, paths: [`${rel}/${PLAYTHROUGH_TEST_FILE}`, `${rel}/${PLAYTHROUGH_ASSEMBLY}.asmdef`] };
}
