/**
 * The play-through test: boot the entry scene, start a session through the
 * game's IPlaythroughDriver, act until it ends, and leave a record of what
 * happened.
 *
 * The generated boot test proves the framework comes up; it drives nothing, so
 * its recording is the un-started game holding still. This test plays. It
 * binds to exactly one contract — Strada.Core.Play.IPlaythroughDriver, which
 * every game built on Strada.Core registers as an adapter over its own flow
 * and input services — so the same generated test serves every game and no
 * game's type names, scene names or rules appear here. A game that registers
 * no driver is recorded as such and fails the test: it cannot be proven
 * playable.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { chooseTestDir, hasTestFramework } from '../unity-scene/boot-smoke-test.js';

export const PLAYTHROUGH_TEST_CLASS = 'StradaPlaythroughTest';
export const PLAYTHROUGH_TEST_FILE = `${PLAYTHROUGH_TEST_CLASS}.cs`;
export const PLAYTHROUGH_RECORD_FILE = 'playthrough.json';
export const PLAYTHROUGH_ASSEMBLY = 'Strada.Generated.PlaythroughTests';
/** The contract the test drives; a game registers one in its service container. */
export const PLAYTHROUGH_DRIVER_TYPE = 'Strada.Core.Play.IPlaythroughDriver';
/** Optional: how many sessions the game offers; lets the run play them all and measure a level count. */
export const PLAYTHROUGH_CATALOG_TYPE = 'Strada.Core.Play.ISessionCatalog';
/** Upper bound on sessions one run plays ("all" on a 200-level game is not one run). */
export const MAX_SESSIONS_PER_RUN = 12;

/** The C# source of the test and its assembly definition. */
export function buildPlaythroughTest(sceneName: string): { source: string; asmdef: string } {
  const source = `// Generated by unity_playthrough. Rewritten on every run; do not edit.
//
// Boots the entry scene, starts a session through the game's
// ${PLAYTHROUGH_DRIVER_TYPE}, acts until the session ends, records checkpoint
// frames, and writes ${PLAYTHROUGH_RECORD_FILE} with what happened.
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using Strada.Core.Bootstrap;
using Strada.Core.Play;

public class ${PLAYTHROUGH_TEST_CLASS}
{
    [Serializable]
    public class Record
    {
        public string scene;
        public int session;
        public string driverType;
        public string missing;
        public string phaseAfterBoot;
        public bool autoStarted;
        public bool startAccepted;
        public List<string> phasesSeen = new List<string>();
        public int actions;
        public string outcome;
        public bool reachedOutcome;
        public int framesCaptured;
        public float elapsedSeconds;
        /// <summary>Scene load start → GameBootstrapper.Services published.</summary>
        public float bootSeconds = -1f;
        /// <summary>Wall time and frame count of the play loop; frames right after a capture (a GPU read-back stall) are not counted.</summary>
        public float playSeconds;
        public int playFrames;
        public float worstFrameMs;
        /// <summary>ISessionCatalog.SessionCount; -1 when the game registers no catalog.</summary>
        public int sessionCount = -1;
        /// <summary>Every session this run played, in order; the top-level fields mirror the first.</summary>
        public List<SessionRecord> sessions = new List<SessionRecord>();
        public List<string> errors = new List<string>();
        /// <summary>What was on screen at the end of play (renderers, bound sprite/mesh names, audio) — code-instantiated included.</summary>
        public RuntimeDump runtime;
    }

    [Serializable]
    public class RuntimeDump
    {
        public int renderers;
        public int worldRenderers;
        public int spriteRenderers;
        public int meshRenderers;
        public int canvases;
        public int particleSystems;
        public int audioSources;
        public int audioPlaying;
        public List<string> sprites = new List<string>();
        public List<string> meshes = new List<string>();
        public int primitiveMeshes;
    }

    /// <summary>What is actually on screen at the end of play: the file scan cannot see what code instantiates.</summary>
    static RuntimeDump DumpRuntime()
    {
        var d = new RuntimeDump();
        try
        {
            var seenSprites = new HashSet<string>();
            var seenMeshes = new HashSet<string>();
            foreach (var r in UnityEngine.Object.FindObjectsByType<Renderer>(FindObjectsSortMode.None))
            {
                d.renderers++;
                var sr = r as SpriteRenderer;
                if (sr != null)
                {
                    d.spriteRenderers++; d.worldRenderers++;
                    var name = sr.sprite != null ? sr.sprite.name : null;
                    if (!string.IsNullOrEmpty(name) && seenSprites.Add(name) && d.sprites.Count < 40) d.sprites.Add(name);
                    continue;
                }
                if (r is MeshRenderer || r is SkinnedMeshRenderer)
                {
                    d.meshRenderers++; d.worldRenderers++;
                    Mesh mesh = null;
                    var smr = r as SkinnedMeshRenderer;
                    if (smr != null) mesh = smr.sharedMesh;
                    else { var mf = r.GetComponent<MeshFilter>(); if (mf != null) mesh = mf.sharedMesh; }
                    var mname = mesh != null ? mesh.name : null;
                    if (!string.IsNullOrEmpty(mname))
                    {
                        if (mname == "Cube" || mname == "Sphere" || mname == "Capsule" || mname == "Cylinder" || mname == "Plane" || mname == "Quad") d.primitiveMeshes++;
                        if (seenMeshes.Add(mname) && d.meshes.Count < 40) d.meshes.Add(mname);
                    }
                    continue;
                }
                if (r is ParticleSystemRenderer || r is TrailRenderer || r is LineRenderer) d.worldRenderers++;
            }
            d.canvases = UnityEngine.Object.FindObjectsByType<Canvas>(FindObjectsSortMode.None).Length;
            d.particleSystems = UnityEngine.Object.FindObjectsByType<ParticleSystem>(FindObjectsSortMode.None).Length;
            foreach (var a in UnityEngine.Object.FindObjectsByType<AudioSource>(FindObjectsSortMode.None))
            {
                d.audioSources++;
                if (a.isPlaying) d.audioPlaying++;
            }
        }
        catch (Exception) { /* a dump that fails leaves zeros; the frames still speak */ }
        return d;
    }

    [Serializable]
    public class SessionRecord
    {
        public int index;
        public bool startAccepted;
        public List<string> phasesSeen = new List<string>();
        public int actions;
        public string outcome;
        public bool reachedOutcome;
        public float seconds;
        public string lastPhase = "";
    }

    /// <summary>"1-3", "2,5", "all" (bounded by the catalog and MAX_SESSIONS_PER_RUN) or a single index; nothing → the default index.</summary>
    static List<int> SessionIndices(string spec, int defaultIndex, int catalogCount)
    {
        var result = new List<int>();
        if (string.IsNullOrEmpty(spec)) { result.Add(defaultIndex); return result; }
        spec = spec.Trim().ToLowerInvariant();
        if (spec == "all")
        {
            if (catalogCount <= 0) { result.Add(defaultIndex); return result; }
            for (var i = 1; i <= Math.Min(catalogCount, ${MAX_SESSIONS_PER_RUN}); i++) result.Add(i);
            return result;
        }
        foreach (var part in spec.Split(','))
        {
            var range = part.Trim().Split('-');
            int a, b;
            if (range.Length == 2 && int.TryParse(range[0], out a) && int.TryParse(range[1], out b))
            {
                for (var i = a; i <= b && result.Count < ${MAX_SESSIONS_PER_RUN}; i++) result.Add(i);
            }
            else if (int.TryParse(part.Trim(), out a) && result.Count < ${MAX_SESSIONS_PER_RUN}) result.Add(a);
        }
        if (result.Count == 0) result.Add(defaultIndex);
        return result;
    }

    static void Mirror(Record record, SessionRecord s)
    {
        record.session = s.index;
        record.startAccepted = s.startAccepted;
        record.actions = s.actions;
        record.outcome = s.outcome;
        record.reachedOutcome = s.reachedOutcome;
        record.phasesSeen = s.phasesSeen;
    }

    const int Width = 1280;
    const int Height = 720;
    const int MaxFrames = 40;
    const int FramesBetweenCaptures = 15;

    static string Env(string name, string fallback)
    {
        var v = Environment.GetEnvironmentVariable(name);
        return string.IsNullOrEmpty(v) ? fallback : v;
    }

    static int EnvInt(string name, int fallback)
    {
        int parsed;
        return int.TryParse(Environment.GetEnvironmentVariable(name), out parsed) ? parsed : fallback;
    }

    static string Phase(IPlaythroughDriver driver)
    {
        try { return driver.Phase ?? "null"; }
        catch (Exception e) { return "error:" + e.GetType().Name; }
    }

    [UnityTest]
    public IEnumerator TheGameCanBePlayedToAnOutcome()
    {
        var record = new Record();
        record.scene = Env("STRADA_PLAYTHROUGH_SCENE", ${JSON.stringify(sceneName)});
        record.session = EnvInt("STRADA_PLAYTHROUGH_SESSION", 1);
        record.driverType = ${JSON.stringify(PLAYTHROUGH_DRIVER_TYPE)};
        var maxActions = EnvInt("STRADA_PLAYTHROUGH_MAX_ACTIONS", 60);
        var deadlineSeconds = EnvInt("STRADA_PLAYTHROUGH_DEADLINE_S", 45);
        var captureDir = Env("STRADA_CAPTURE_DIR", null);
        var jsonPath = Env("STRADA_PLAYTHROUGH_JSON", captureDir == null ? null : Path.Combine(captureDir, ${JSON.stringify(PLAYTHROUGH_RECORD_FILE)}));
        var started = Time.realtimeSinceStartup;

        Application.LogCallback watch = (condition, stackTrace, type) =>
        {
            if ((type == LogType.Error || type == LogType.Exception || type == LogType.Assert) && record.errors.Count < 20)
                record.errors.Add("[" + type + "] " + condition);
        };
        Application.logMessageReceived += watch;
        LogAssert.ignoreFailingMessages = true;

        RenderTexture target = null;
        Texture2D readback = null;
        Camera camera = null;
        var overlays = new List<Canvas>();
        try
        {
            if (!Application.CanStreamedLevelBeLoaded(record.scene))
            {
                record.missing = "scene " + record.scene + " is not in Build Settings";
                Assert.Fail(record.missing);
            }
            var loadStarted = Time.realtimeSinceStartup;
            yield return SceneManager.LoadSceneAsync(record.scene, LoadSceneMode.Single);

            // A headless first boot loads the scene, imports what the editor
            // never touched and compiles shaders before the bootstrapper runs;
            // 30 s by default, overridable per run.
            var bootSeconds = EnvInt("STRADA_PLAYTHROUGH_BOOT_DEADLINE_S", 30);
            var bootDeadline = Time.realtimeSinceStartup + bootSeconds;
            while (Time.realtimeSinceStartup < bootDeadline && GameBootstrapper.Services == null)
                yield return null;
            if (GameBootstrapper.Services != null) record.bootSeconds = Time.realtimeSinceStartup - loadStarted;
            if (GameBootstrapper.Services == null)
            {
                record.missing = "GameBootstrapper.Services stayed null for " + bootSeconds + " s — the entry scene holds no GameBootstrapper, or its config is unassigned, or a module threw while starting";
                Assert.Fail(record.missing);
            }

            IPlaythroughDriver driver = null;
            var serviceDeadline = Time.realtimeSinceStartup + 10f;
            while (Time.realtimeSinceStartup < serviceDeadline && driver == null)
            {
                try { GameBootstrapper.Services.TryGet(out driver); } catch { driver = null; }
                if (driver == null) yield return null;
            }
            if (driver == null)
            {
                record.missing = "the game registers no " + record.driverType + " — it cannot be played by the framework";
                Assert.Fail(record.missing);
            }

            // Does the game start play by itself? Two seconds of idling answer that.
            var idleDeadline = Time.realtimeSinceStartup + 2f;
            while (Time.realtimeSinceStartup < idleDeadline) yield return null;
            record.phaseAfterBoot = Phase(driver);
            try { record.autoStarted = driver.IsSessionActive; } catch { record.autoStarted = false; }
            ISessionCatalog catalog = null;
            try { GameBootstrapper.Services.TryGet(out catalog); } catch { catalog = null; }
            if (catalog != null)
            {
                try { record.sessionCount = catalog.SessionCount; }
                catch (Exception e) { if (record.errors.Count < 20) record.errors.Add("[SessionCount] " + e.GetType().Name + ": " + e.Message); }
            }

            if (captureDir != null)
            {
                Directory.CreateDirectory(captureDir);
                camera = Camera.main != null ? Camera.main : (Camera.allCameras.Length > 0 ? Camera.allCameras[0] : null);
                if (camera != null)
                {
                    target = new RenderTexture(Width, Height, 24);
                    readback = new Texture2D(Width, Height, TextureFormat.RGB24, false);
                    foreach (var canvas in UnityEngine.Object.FindObjectsByType<Canvas>(FindObjectsSortMode.None))
                        if (canvas.renderMode == RenderMode.ScreenSpaceOverlay) overlays.Add(canvas);
                    foreach (var canvas in overlays)
                    {
                        canvas.renderMode = RenderMode.ScreenSpaceCamera;
                        canvas.worldCamera = camera;
                    }
                }
            }
            Capture(record, captureDir, camera, target, readback);

            // One pass per requested session. The first may already be running
            // (the game starts play by itself); every later one is started by the
            // driver after a few settling frames. A session that never ends stops
            // the run — the sessions after it were not proven either way.
            var indices = SessionIndices(Env("STRADA_PLAYTHROUGH_SESSIONS", null), record.session, record.sessionCount);
            var frame = 0;
            var wallPlaySeconds = 0f;
            for (var si = 0; si < indices.Count; si++)
            {
                var s = new SessionRecord { index = indices[si] };
                record.sessions.Add(s);
                if (si == 0 && record.autoStarted)
                    s.startAccepted = true;
                else
                {
                    if (si > 0) for (var settle = 0; settle < 5; settle++) yield return null;
                    try { s.startAccepted = driver.StartSession(s.index); }
                    catch (Exception e)
                    {
                        s.startAccepted = false;
                        if (record.errors.Count < 20) record.errors.Add("[StartSession " + s.index + "] " + e.GetType().Name + ": " + e.Message);
                    }
                }
                if (si == 0) Mirror(record, s);
                yield return null;
                if (!s.startAccepted) { s.outcome = "None"; if (si == 0) Mirror(record, s); break; }

                var playDeadline = Time.realtimeSinceStartup + deadlineSeconds;
                var playStarted = Time.realtimeSinceStartup;
                var last = "";
                var skipDelta = true; // the first delta belongs to StartSession's frame
                while (Time.realtimeSinceStartup < playDeadline)
                {
                    if (!skipDelta)
                    {
                        var ms = Time.unscaledDeltaTime * 1000f;
                        record.playFrames++;
                        record.playSeconds += Time.unscaledDeltaTime;
                        if (ms > record.worstFrameMs) record.worstFrameMs = ms;
                    }
                    skipDelta = false;
                    var phase = Phase(driver);
                    if (phase != last) { s.phasesSeen.Add(phase); last = phase; }
                    PlaythroughOutcome outcome;
                    try { outcome = driver.Outcome; } catch { outcome = PlaythroughOutcome.None; }
                    if (outcome != PlaythroughOutcome.None)
                    {
                        s.outcome = outcome.ToString();
                        s.reachedOutcome = true;
                        break;
                    }
                    if (s.actions < maxActions)
                    {
                        try { if (driver.Act()) s.actions++; }
                        catch (Exception e) { if (record.errors.Count < 20) record.errors.Add("[Act] " + e.GetType().Name + ": " + e.Message); }
                    }
                    yield return null;
                    frame++;
                    if (frame % FramesBetweenCaptures == 0) { Capture(record, captureDir, camera, target, readback); skipDelta = true; }
                }
                s.seconds = Time.realtimeSinceStartup - playStarted;
                wallPlaySeconds += s.seconds;
                s.lastPhase = last;
                if (!s.reachedOutcome) s.outcome = "None";
                if (si == 0) Mirror(record, s);
                if (!s.reachedOutcome) break;
            }
            if (record.playFrames == 0) record.playSeconds = wallPlaySeconds;
            record.runtime = DumpRuntime();
            Capture(record, captureDir, camera, target, readback);

            foreach (var s in record.sessions)
                Assert.IsTrue(s.startAccepted, "The driver refused to start session " + s.index + ".");
            foreach (var s in record.sessions)
                Assert.IsTrue(
                    s.reachedOutcome,
                    "Session " + s.index + " never ended after " + s.actions + " actions in " + deadlineSeconds
                    + " s; last phase " + s.lastPhase + ".");
        }
        finally
        {
            record.elapsedSeconds = Time.realtimeSinceStartup - started;
            Application.logMessageReceived -= watch;
            LogAssert.ignoreFailingMessages = false;
            foreach (var canvas in overlays)
            {
                if (canvas == null) continue;
                canvas.renderMode = RenderMode.ScreenSpaceOverlay;
                canvas.worldCamera = null;
            }
            if (camera != null) camera.targetTexture = null;
            RenderTexture.active = null;
            if (target != null) target.Release();
            if (jsonPath != null)
            {
                try
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(jsonPath));
                    File.WriteAllText(jsonPath, JsonUtility.ToJson(record, true));
                }
                catch (Exception e) { Debug.LogWarning("playthrough record not written: " + e.Message); }
            }
        }
    }

    static void Capture(Record record, string dir, Camera camera, RenderTexture target, Texture2D readback)
    {
        if (dir == null || camera == null || target == null || readback == null || record.framesCaptured >= MaxFrames) return;
        try
        {
            var previous = camera.targetTexture;
            camera.targetTexture = target;
            camera.Render();
            RenderTexture.active = target;
            readback.ReadPixels(new Rect(0, 0, Width, Height), 0, 0);
            readback.Apply();
            RenderTexture.active = null;
            camera.targetTexture = previous;
            File.WriteAllBytes(Path.Combine(dir, "frame_" + record.framesCaptured.ToString("D5") + ".png"), readback.EncodeToPNG());
            record.framesCaptured++;
        }
        catch (Exception e)
        {
            if (record.errors.Count < 20) record.errors.Add("[Capture] " + e.GetType().Name + ": " + e.Message);
        }
    }
}
`;
  const asmdef = JSON.stringify(
    {
      name: PLAYTHROUGH_ASSEMBLY,
      rootNamespace: '',
      references: ['Strada.Core', 'UnityEngine.TestRunner', 'UnityEditor.TestRunner'],
      includePlatforms: [],
      excludePlatforms: [],
      allowUnsafeCode: false,
      // Same shape as the boot test's asmdef: overrideReferences drops the
      // engine modules the capture needs (measured there, CS0103 on ScreenCapture).
      overrideReferences: false,
      precompiledReferences: [],
      autoReferenced: false,
      defineConstraints: ['UNITY_INCLUDE_TESTS'],
      versionDefines: [],
      noEngineReferences: false,
    },
    null,
    2,
  );
  return { source, asmdef };
}

export interface PlaythroughEmission {
  readonly written: boolean;
  readonly reason?: string;
  readonly paths: string[];
  readonly dir?: string;
}

/**
 * Write the test beside the generated boot test, in its own folder so the two
 * assemblies do not share one directory (Unity allows one asmdef per folder).
 */
export function emitPlaythroughTest(projectPath: string, sceneName: string): PlaythroughEmission {
  if (!hasTestFramework(projectPath)) {
    return {
      written: false,
      reason: 'com.unity.test-framework is not in Packages/manifest.json — no play-mode test can compile, so none was written.',
      paths: [],
    };
  }
  const base = chooseTestDir(projectPath) ?? join(projectPath, 'Assets/Tests/PlayMode');
  const dir = join(base, 'Playthrough');
  const { source, asmdef } = buildPlaythroughTest(sceneName);
  try {
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, PLAYTHROUGH_TEST_FILE), source);
    writeFileSync(join(dir, `${PLAYTHROUGH_ASSEMBLY}.asmdef`), asmdef);
  } catch (error) {
    return { written: false, reason: `could not write the play-through test: ${String(error)}`, paths: [] };
  }
  const rel = dir.slice(projectPath.length + 1).replace(/\\/g, '/');
  return { written: true, dir, paths: [`${rel}/${PLAYTHROUGH_TEST_FILE}`, `${rel}/${PLAYTHROUGH_ASSEMBLY}.asmdef`] };
}
