/**
 * The play-through test: boot the entry scene, start a level, play it with the
 * game's own input service until it ends, and leave a record of what happened.
 *
 * The generated boot test proves the framework comes up; it drives nothing, so
 * its recording is the un-started board holding still. Measured 2026-09-10 on
 * PixelFlow: nothing outside a test ever calls StartLevel, so "the game boots"
 * and "the game can be played" were two different facts and only the first
 * was ever measured.
 *
 * The test binds to the game through reflection — type names, not assembly
 * references — so the generated assembly needs no reference to the game's
 * modules and one generator serves every Strada project: the flow service
 * (StartLevel / State) and the input service (CanTapConveyor / TapConveyor)
 * are named by the caller and default to the Strada.Core conventions.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  BOOT_TEST_ASSEMBLY,
  chooseTestDir,
  hasTestFramework,
} from '../unity-scene/boot-smoke-test.js';

export const PLAYTHROUGH_TEST_CLASS = 'StradaPlaythroughTest';
export const PLAYTHROUGH_TEST_FILE = `${PLAYTHROUGH_TEST_CLASS}.cs`;
export const PLAYTHROUGH_RECORD_FILE = 'playthrough.json';
export const PLAYTHROUGH_ASSEMBLY = 'Strada.Generated.PlaythroughTests';

export interface PlaythroughBinding {
  /** Full type name of the game-flow service, resolved through GameBootstrapper.Services. */
  readonly flowType: string;
  /** Full type name of the input service. */
  readonly inputType: string;
  readonly startMethod: string;
  readonly stateProperty: string;
  readonly canTapMethod: string;
  readonly tapMethod: string;
  /** State names that end a level, e.g. LevelWon, LevelFailed. */
  readonly terminalStates: readonly string[];
}

export const DEFAULT_BINDING: PlaythroughBinding = {
  flowType: 'YourGame.PixelFlow.GameFlow.IGameFlowService',
  inputType: 'YourGame.PixelFlow.Input.IInputService',
  startMethod: 'StartLevel',
  stateProperty: 'State',
  canTapMethod: 'CanTapConveyor',
  tapMethod: 'TapConveyor',
  terminalStates: ['LevelWon', 'LevelFailed'],
};

/** The C# source of the test and its assembly definition. */
export function buildPlaythroughTest(
  sceneName: string,
  binding: PlaythroughBinding = DEFAULT_BINDING,
): { source: string; asmdef: string } {
  const terminal = binding.terminalStates.map((s) => JSON.stringify(s)).join(', ');
  const source = `// Generated by unity_playthrough. Rewritten on every run; do not edit.
//
// Boots the entry scene, starts a level through the game's flow service, plays
// it with the game's input service until it reaches a terminal state, records
// checkpoint frames, and writes ${PLAYTHROUGH_RECORD_FILE} with what happened.
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using Strada.Core.Bootstrap;

public class ${PLAYTHROUGH_TEST_CLASS}
{
    [Serializable]
    public class Record
    {
        public string scene;
        public int level;
        public string flowType;
        public string inputType;
        public string missing;
        public string stateAfterBoot;
        public bool autoStarted;
        public bool startAccepted;
        public List<string> statesSeen = new List<string>();
        public int tapsDriven;
        public string terminalState;
        public bool reachedTerminal;
        public int framesCaptured;
        public float elapsedSeconds;
        public List<string> errors = new List<string>();
    }

    const int Width = 1280;
    const int Height = 720;
    const int MaxFrames = 40;
    const int FramesBetweenCaptures = 15;

    static string Env(string name, string fallback)
    {
        var v = Environment.GetEnvironmentVariable(name);
        return string.IsNullOrEmpty(v) ? fallback : v;
    }

    static int EnvInt(string name, int fallback)
    {
        int parsed;
        return int.TryParse(Environment.GetEnvironmentVariable(name), out parsed) ? parsed : fallback;
    }

    static Type FindType(string fullName)
    {
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            Type t = null;
            try { t = assembly.GetType(fullName, false); } catch { }
            if (t != null) return t;
        }
        return null;
    }

    /// Resolve a service by type through GameBootstrapper.Services.TryGet<T>(out T).
    static object Resolve(Type serviceType)
    {
        var services = GameBootstrapper.Services;
        if (services == null || serviceType == null) return null;
        foreach (var m in services.GetType().GetMethods(BindingFlags.Public | BindingFlags.Instance))
        {
            if (m.Name != "TryGet" || !m.IsGenericMethodDefinition || m.GetParameters().Length != 1) continue;
            try
            {
                var closed = m.MakeGenericMethod(serviceType);
                var args = new object[] { null };
                var ok = (bool)closed.Invoke(services, args);
                if (ok && args[0] != null) return args[0];
            }
            catch { }
        }
        return null;
    }

    static string StateName(object flow, PropertyInfo state)
    {
        try { var v = state.GetValue(flow, null); return v == null ? "null" : v.ToString(); }
        catch (Exception e) { return "error:" + e.GetType().Name; }
    }

    [UnityTest]
    public IEnumerator TheGameCanBePlayedToATerminalState()
    {
        var record = new Record();
        record.scene = Env("STRADA_PLAYTHROUGH_SCENE", ${JSON.stringify(sceneName)});
        record.level = EnvInt("STRADA_PLAYTHROUGH_LEVEL", 1);
        record.flowType = Env("STRADA_PLAYTHROUGH_FLOW_TYPE", ${JSON.stringify(binding.flowType)});
        record.inputType = Env("STRADA_PLAYTHROUGH_INPUT_TYPE", ${JSON.stringify(binding.inputType)});
        var maxTaps = EnvInt("STRADA_PLAYTHROUGH_MAX_TAPS", 60);
        var deadlineSeconds = EnvInt("STRADA_PLAYTHROUGH_DEADLINE_S", 45);
        var captureDir = Env("STRADA_CAPTURE_DIR", null);
        var jsonPath = Env("STRADA_PLAYTHROUGH_JSON", captureDir == null ? null : Path.Combine(captureDir, ${JSON.stringify(PLAYTHROUGH_RECORD_FILE)}));
        var terminal = new HashSet<string> { ${terminal} };
        var started = Time.realtimeSinceStartup;

        Application.LogCallback watch = (condition, stackTrace, type) =>
        {
            if ((type == LogType.Error || type == LogType.Exception || type == LogType.Assert) && record.errors.Count < 20)
                record.errors.Add("[" + type + "] " + condition);
        };
        Application.logMessageReceived += watch;
        LogAssert.ignoreFailingMessages = true;

        RenderTexture target = null;
        Texture2D readback = null;
        Camera camera = null;
        var overlays = new List<Canvas>();
        try
        {
            if (!Application.CanStreamedLevelBeLoaded(record.scene))
            {
                record.missing = "scene " + record.scene + " is not in Build Settings";
                Assert.Fail(record.missing);
            }
            yield return SceneManager.LoadSceneAsync(record.scene, LoadSceneMode.Single);

            var bootDeadline = Time.realtimeSinceStartup + 10f;
            while (Time.realtimeSinceStartup < bootDeadline && GameBootstrapper.Services == null)
                yield return null;
            if (GameBootstrapper.Services == null)
            {
                record.missing = "GameBootstrapper.Services stayed null for 10 s";
                Assert.Fail(record.missing);
            }

            var flowType = FindType(record.flowType);
            var inputType = FindType(record.inputType);
            if (flowType == null || inputType == null)
            {
                record.missing = "type not found: " + (flowType == null ? record.flowType : record.inputType);
                Assert.Fail(record.missing);
            }
            object flow = null;
            object input = null;
            var serviceDeadline = Time.realtimeSinceStartup + 10f;
            while (Time.realtimeSinceStartup < serviceDeadline && (flow == null || input == null))
            {
                flow = flow ?? Resolve(flowType);
                input = input ?? Resolve(inputType);
                if (flow == null || input == null) yield return null;
            }
            if (flow == null || input == null)
            {
                record.missing = "service not resolvable: " + (flow == null ? record.flowType : record.inputType);
                Assert.Fail(record.missing);
            }

            var state = flowType.GetProperty(${JSON.stringify(binding.stateProperty)});
            var start = flowType.GetMethod(${JSON.stringify(binding.startMethod)}, new[] { typeof(int) });
            var canTap = inputType.GetMethod(${JSON.stringify(binding.canTapMethod)}, new[] { typeof(int) });
            var tap = inputType.GetMethod(${JSON.stringify(binding.tapMethod)}, new[] { typeof(int) });
            if (state == null || start == null || canTap == null || tap == null)
            {
                record.missing = "member not found on the bound services (" +
                    (state == null ? ${JSON.stringify(binding.stateProperty)} : start == null ? ${JSON.stringify(binding.startMethod)} : canTap == null ? ${JSON.stringify(binding.canTapMethod)} : ${JSON.stringify(binding.tapMethod)}) + ")";
                Assert.Fail(record.missing);
            }

            // Does the game start itself? Two seconds of idling answer that.
            var idleDeadline = Time.realtimeSinceStartup + 2f;
            while (Time.realtimeSinceStartup < idleDeadline) yield return null;
            record.stateAfterBoot = StateName(flow, state);
            record.autoStarted = record.stateAfterBoot == "Playing" || record.stateAfterBoot == "LevelStarting";

            if (captureDir != null)
            {
                Directory.CreateDirectory(captureDir);
                camera = Camera.main != null ? Camera.main : (Camera.allCameras.Length > 0 ? Camera.allCameras[0] : null);
                if (camera != null)
                {
                    target = new RenderTexture(Width, Height, 24);
                    readback = new Texture2D(Width, Height, TextureFormat.RGB24, false);
                    foreach (var canvas in UnityEngine.Object.FindObjectsByType<Canvas>(FindObjectsSortMode.None))
                        if (canvas.renderMode == RenderMode.ScreenSpaceOverlay) overlays.Add(canvas);
                    foreach (var canvas in overlays)
                    {
                        canvas.renderMode = RenderMode.ScreenSpaceCamera;
                        canvas.worldCamera = camera;
                    }
                }
            }
            Capture(record, captureDir, camera, target, readback);

            if (record.autoStarted)
                record.startAccepted = true;
            else
            {
                var accepted = start.Invoke(flow, new object[] { record.level });
                record.startAccepted = accepted is bool ? (bool)accepted : true;
            }
            yield return null;

            var playDeadline = Time.realtimeSinceStartup + deadlineSeconds;
            var frame = 0;
            var last = "";
            while (Time.realtimeSinceStartup < playDeadline)
            {
                var name = StateName(flow, state);
                if (name != last) { record.statesSeen.Add(name); last = name; }
                if (terminal.Contains(name)) { record.terminalState = name; record.reachedTerminal = true; break; }
                if (record.tapsDriven < maxTaps)
                {
                    bool can = false;
                    try { can = (bool)canTap.Invoke(input, new object[] { 0 }); } catch { }
                    if (can)
                    {
                        try { tap.Invoke(input, new object[] { 0 }); record.tapsDriven++; }
                        catch (Exception e) { if (record.errors.Count < 20) record.errors.Add("[Tap] " + e.GetType().Name + ": " + e.Message); }
                    }
                }
                yield return null;
                frame++;
                if (frame % FramesBetweenCaptures == 0) Capture(record, captureDir, camera, target, readback);
            }
            if (!record.reachedTerminal) record.terminalState = StateName(flow, state);
            Capture(record, captureDir, camera, target, readback);

            Assert.IsTrue(record.startAccepted, "The flow service refused to start level " + record.level + ".");
            Assert.IsTrue(
                record.reachedTerminal,
                "Level " + record.level + " never reached a terminal state (" + string.Join("/", terminal) + ") after "
                + record.tapsDriven + " taps in " + deadlineSeconds + " s; last state " + record.terminalState + ".");
        }
        finally
        {
            record.elapsedSeconds = Time.realtimeSinceStartup - started;
            Application.logMessageReceived -= watch;
            LogAssert.ignoreFailingMessages = false;
            foreach (var canvas in overlays)
            {
                if (canvas == null) continue;
                canvas.renderMode = RenderMode.ScreenSpaceOverlay;
                canvas.worldCamera = null;
            }
            if (camera != null) camera.targetTexture = null;
            RenderTexture.active = null;
            if (target != null) target.Release();
            if (jsonPath != null)
            {
                try
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(jsonPath));
                    File.WriteAllText(jsonPath, JsonUtility.ToJson(record, true));
                }
                catch (Exception e) { Debug.LogWarning("playthrough record not written: " + e.Message); }
            }
        }
    }

    static void Capture(Record record, string dir, Camera camera, RenderTexture target, Texture2D readback)
    {
        if (dir == null || camera == null || target == null || readback == null || record.framesCaptured >= MaxFrames) return;
        try
        {
            var previous = camera.targetTexture;
            camera.targetTexture = target;
            camera.Render();
            RenderTexture.active = target;
            readback.ReadPixels(new Rect(0, 0, Width, Height), 0, 0);
            readback.Apply();
            RenderTexture.active = null;
            camera.targetTexture = previous;
            File.WriteAllBytes(Path.Combine(dir, "frame_" + record.framesCaptured.ToString("D5") + ".png"), readback.EncodeToPNG());
            record.framesCaptured++;
        }
        catch (Exception e)
        {
            if (record.errors.Count < 20) record.errors.Add("[Capture] " + e.GetType().Name + ": " + e.Message);
        }
    }
}
`;
  const asmdef = JSON.stringify(
    {
      name: PLAYTHROUGH_ASSEMBLY,
      rootNamespace: '',
      references: ['Strada.Core', 'UnityEngine.TestRunner', 'UnityEditor.TestRunner'],
      includePlatforms: [],
      excludePlatforms: [],
      allowUnsafeCode: false,
      // Same shape as the boot test's asmdef: overrideReferences drops the
      // engine modules the capture needs (measured there, CS0103 on ScreenCapture).
      overrideReferences: false,
      precompiledReferences: [],
      autoReferenced: false,
      defineConstraints: ['UNITY_INCLUDE_TESTS'],
      versionDefines: [],
      noEngineReferences: false,
    },
    null,
    2,
  );
  return { source, asmdef };
}

export interface PlaythroughEmission {
  readonly written: boolean;
  readonly reason?: string;
  readonly paths: string[];
  readonly dir?: string;
}

/**
 * Write the test beside the generated boot test, in its own folder so the two
 * assemblies do not share one directory (Unity allows one asmdef per folder).
 */
export function emitPlaythroughTest(
  projectPath: string,
  sceneName: string,
  binding: PlaythroughBinding = DEFAULT_BINDING,
): PlaythroughEmission {
  if (!hasTestFramework(projectPath)) {
    return {
      written: false,
      reason:
        'com.unity.test-framework is not in Packages/manifest.json — no play-mode test can compile, so none was written.',
      paths: [],
    };
  }
  const base = chooseTestDir(projectPath) ?? join(projectPath, 'Assets/Tests/PlayMode');
  const dir = join(base, 'Playthrough');
  const { source, asmdef } = buildPlaythroughTest(sceneName, binding);
  try {
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, PLAYTHROUGH_TEST_FILE), source);
    writeFileSync(join(dir, `${PLAYTHROUGH_ASSEMBLY}.asmdef`), asmdef);
  } catch (error) {
    return {
      written: false,
      reason: `could not write the play-through test: ${String(error)}`,
      paths: [],
    };
  }
  const rel = dir.slice(projectPath.length + 1).replace(/\\/g, '/');
  return {
    written: true,
    dir,
    paths: [`${rel}/${PLAYTHROUGH_TEST_FILE}`, `${rel}/${PLAYTHROUGH_ASSEMBLY}.asmdef`],
  };
}

/** The boot-test assembly name is re-exported so a caller can tell the two generated assemblies apart. */
export { BOOT_TEST_ASSEMBLY };
