import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The one test that proves an assembled scene is a game.
 *
 * Assembling a scene and verifying its YAML on disk shows that the references
 * are real links. It does not show that the game runs: a bootstrapper can be
 * wired to a config whose module list throws on the first frame, and the scene
 * file looks identical either way.
 *
 * Nothing else in the pipeline supplies this. Measured on two full runs, every
 * generated test assembly was an empty directory, so a headless PlayMode run
 * executed zero tests and Unity still reported `result="Passed"`. A verifier
 * with nothing to run is not a verifier, so the builder that assembles the scene
 * leaves behind the test that boots it.
 *
 * It asserts only what Strada.Core actually exposes — GameBootstrapper's
 * IsInitialized and its static Services — so it holds for any game built on the
 * framework, without knowing anything about this one.
 */

/** Where the generated check lives, relative to the project root. */
export const BOOT_TEST_DIR = 'Assets/Tests/PlayMode';
export const BOOT_TEST_ASSEMBLY = 'Strada.Generated.PlayModeTests';

export function buildBootSmokeTest(sceneName: string): { source: string; asmdef: string } {
  const source = `// Generated by unity_scene_build. Regenerated whenever the scene is reassembled.
//
// Boots the assembled scene in play mode and asserts the framework came up.
// Edit freely: this file is only rewritten when the scene is rebuilt.
using System.Collections;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.TestTools;
using Strada.Core.Bootstrap;

public class StradaBootSmokeTest
{
    [UnityTest]
    public IEnumerator TheAssembledSceneBootsWithoutError()
    {
        yield return SceneManager.LoadSceneAsync(${JSON.stringify(sceneName)}, LoadSceneMode.Single);

        // Awake, Start and the bootstrapper's own initialization span several
        // frames; asserting on the first one reads a half-built world.
        for (var frame = 0; frame < 10; frame++) yield return null;

        var bootstrapper = Object.FindFirstObjectByType<GameBootstrapper>();
        Assert.IsNotNull(
            bootstrapper,
            "The scene loaded but holds no GameBootstrapper, so nothing starts the modules.");

        Assert.IsTrue(
            bootstrapper.IsInitialized,
            "GameBootstrapper is in the scene but never finished initializing. "
            + "Its _gameConfig is usually unassigned, or a module threw while starting.");

        Assert.IsNotNull(
            GameBootstrapper.Services,
            "The bootstrapper initialized without publishing a service locator, "
            + "so nothing can resolve a service at runtime.");

        // Fails the test on any error or exception logged during the frames
        // above, including ones no assertion was watching for.
        LogAssert.NoUnexpectedReceived();
    }
}
`;

  const asmdef = JSON.stringify(
    {
      name: BOOT_TEST_ASSEMBLY,
      rootNamespace: '',
      references: ['Strada.Core', 'UnityEngine.TestRunner', 'UnityEditor.TestRunner'],
      includePlatforms: [],
      excludePlatforms: [],
      allowUnsafeCode: false,
      overrideReferences: true,
      precompiledReferences: ['nunit.framework.dll'],
      autoReferenced: false,
      defineConstraints: ['UNITY_INCLUDE_TESTS'],
      versionDefines: [],
      noEngineReferences: false,
    },
    null,
    2,
  );

  return { source, asmdef };
}

/**
 * Is the Test Framework actually installed?
 *
 * Without it, an .asmdef referencing UnityEngine.TestRunner does not merely fail
 * to run — it fails to resolve, and Unity refuses to compile the project at all.
 * Adding a test must never be what breaks the build, so this is checked before
 * anything is written.
 */
export function hasTestFramework(projectPath: string): boolean {
  const manifest = join(projectPath, 'Packages', 'manifest.json');
  try {
    return readFileSync(manifest, 'utf8').includes('com.unity.test-framework');
  } catch {
    return false;
  }
}

export interface BootTestEmission {
  readonly written: boolean;
  readonly reason?: string;
  readonly paths: string[];
}

/** Writes the boot check into the project, or explains why it did not. */
export function emitBootSmokeTest(projectPath: string, sceneName: string): BootTestEmission {
  if (!hasTestFramework(projectPath)) {
    return {
      written: false,
      reason:
        'com.unity.test-framework is not in Packages/manifest.json — a test assembly referencing ' +
        'UnityEngine.TestRunner would stop the whole project compiling, so no boot test was written.',
      paths: [],
    };
  }

  const dir = join(projectPath, BOOT_TEST_DIR);
  const { source, asmdef } = buildBootSmokeTest(sceneName);
  const sourcePath = join(dir, 'StradaBootSmokeTest.cs');
  const asmdefPath = join(dir, `${BOOT_TEST_ASSEMBLY}.asmdef`);

  try {
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(sourcePath, source);
    writeFileSync(asmdefPath, asmdef);
  } catch (error) {
    return { written: false, reason: `could not write the boot test: ${String(error)}`, paths: [] };
  }

  return { written: true, paths: [`${BOOT_TEST_DIR}/StradaBootSmokeTest.cs`, `${BOOT_TEST_DIR}/${BOOT_TEST_ASSEMBLY}.asmdef`] };
}
